# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GetPixelColorButton = QtWidgets.QPushButton(self.centralwidget)
        self.GetPixelColorButton.setGeometry(QtCore.QRect(270, 410, 113, 32))
        self.GetPixelColorButton.setMouseTracking(True)
        self.GetPixelColorButton.setObjectName("GetPixelColorButton")
        self.ColorValue = QtWidgets.QLabel(self.centralwidget)
        self.ColorValue.setGeometry(QtCore.QRect(243, 320, 201, 41))
        self.ColorValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ColorValue.setObjectName("ColorValue")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(160, 50, 200, 200))
        self.Image.setFrameShape(QtWidgets.QFrame.Box)
        self.Image.setAlignment(QtCore.Qt.AlignCenter)
        self.Image.setObjectName("Image")
        self.ShowColor = QtWidgets.QLabel(self.centralwidget)
        self.ShowColor.setGeometry(QtCore.QRect(380, 110, 81, 71))
        self.ShowColor.setFrameShape(QtWidgets.QFrame.Box)
        self.ShowColor.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ShowColor.setAlignment(QtCore.Qt.AlignCenter)
        self.ShowColor.setObjectName("ShowColor")
        self.MousePosition = QtWidgets.QLabel(self.centralwidget)
        self.MousePosition.setGeometry(QtCore.QRect(236, 270, 191, 41))
        self.MousePosition.setObjectName("MousePosition")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GetPixelColorButton.setText(_translate("MainWindow", "取色"))
        self.ColorValue.setText(_translate("MainWindow", "RGBA"))
        self.Image.setText(_translate("MainWindow", "Image"))
        self.ShowColor.setText(_translate("MainWindow", "Color"))
        self.MousePosition.setText(_translate("MainWindow", "Position"))
